var data = {
    author:"",
    time:"",
    business_income:{
        m:0,y:0,
        main:{m:0,y:0},
        other:{m:0,y:0}
    },
    business_cost:{
        m:0,y:0,
        main:{
            staff_emolument:{
                m:0,y:0,
                emolument:{m:0,y:0},
                service_fee:{m:0,y:0},
                emolument_extra:{
                    welfare:{
                        m:0,y:0,
                        moneyness:{m:0,y:0},
                        non_moneyness:{
                            m:0,y:0,
                            using_right_property_depreciation:{m:0,y:0},
                            depreciation:{m:0,y:0},
                            rent:{m:0,y:0}
                        }
                    },
                    house_fund:{m:0,y:0},
                    social_insurance:{
                        m:0,y:0,
                        enterprise_year_fund:{m:0,y:0},
                    },
                    union_fund:{m:0,y:0},
                    staff_education:{m:0,y:0},
                    work_protect:{m:0,y:0},
                    other:{m:0,y:0}
                }
            },
            depreciation:{m:0,y:0},
            fix_cost:{
                m:0,y:0,
                house_fix:{m:0,y:0},
                car_fix:{m:0,y:0},
                equipment_fix:{m:0,y:0},
                other_fix:{m:0,y:0}
            },
            low_value_depreciation_amortize:{
                m:0,y:0,
                instrument:{m:0,y:0}
            },
            circuit_network_rent:{
                m:0,y:0,
                circuit_rent:{m:0,y:0},
                network_rent:{m:0,y:0},
                other:{m:0,y:0}
            },
            water_electric_warm:{m:0,y:0},
            power:{m:0,y:0},
            business_articles:{m:0,y:0},
            car_drive:{m:0,y:0},
            post_communicate:{m:0,y:0},
            insurance:{m:0,y:0},
            trip_fee:{m:0,y:0},
            book_document_fee:{m:0,y:0},
            tenement_manage_cost:{m:0,y:0},
            officail_work:{m:0,y:0},
            meeting:{m:0,y:0},
            business_outsourcing:{m:0,y:0},
            safety_protect:{m:0,y:0},
            traffic:{m:0,y:0},
            system_integration:{m:0,y:0},
            rent:{
                m:0,y:0,
                house_rent:{m:0,y:0},
                car_rent:{m:0,y:0}
            },
            material:{m:0,y:0},
            business_technology_support:{m:0,y:0},
            intangible_assets_amortize:{
                m:0,y:0,
                land_using_right:{m:0,y:0}
            },
            service_outsourcing:{m:0,y:0},
            in_network_settle_account_fee:{m:0,y:0},
            between_network_settle_account_fee:{m:0,y:0},
            resource_using:{m:0,y:0},
            TCT_fee:{m:0,y:0},
            safety_product_fee:{m:0,y:0},
            using_right_property_depreciation:{
                m:0,y:0,
                house_using_right:{m:0,y:0},
                groud_using_right:{m:0,y:0},
            },
            non_rent_using_fee:{
                m:0,y:0,
                groud_service:{m:0,y:0},
                car_service:{m:0,y:0},
                equipment_service:{m:0,y:0},
                other_service:{m:0,y:0}
            },
            circuit_network_service:{m:0,y:0},
            other:{m:0,y:0}
        },
        other:{
            staff_emolument:{
                m:0,y:0,
                emolument:{m:0,y:0},
                service_fee:{m:0,y:0},
                emolument_extra:{
                    welfare:{
                        m:0,y:0,
                        moneyness:{m:0,y:0},
                        non_moneyness:{
                            m:0,y:0,
                            using_right_property_depreciation:{m:0,y:0},
                            depreciation:{m:0,y:0},
                            rent:{m:0,y:0}
                        }
                    },
                    house_fund:{m:0,y:0},
                    social_insurance:{m:0,y:0},
                    union_fund:{m:0,y:0},
                    staff_education:{m:0,y:0},
                    work_protect:{m:0,y:0},
                    other:{m:0,y:0}
                }
            },
            depreciation:{m:0,y:0},
            sell_terminal_commodity:{
                m:0,y:0,
                cellphone:{m:0,y:0}
            },
            sell_equipment:{m:0,y:0},
            rent_business_cost:{
                using_right_property_depreciation:{m:0,y:0}
            },
            softwore_service_cost:{m:0,y:0},
            tenement_manage_cost:{m:0,y:0},
            physica_distribution_service:{m:0,y:0},
            other:{m:0,y:0}
        }
    },
    tax_and_extra:{m:0,y:0},
    sell_fee:{
        m:0,y:0,
        exhibition_fee:{m:0,y:0},
        advertisement_fee:{m:0,y:0},
        business_publicity:{m:0,y:0},
        promotion_fee:{m:0,y:0},
        social_channel_handle_fee:{m:0,y:0},
        social_channel_service_fee:{m:0,y:0},
        market_outsourcing_fee:{m:0,y:0},
        arreara_urge_fee:{m:0,y:0},
        custommer_service:{m:0,y:0}
    },
    manage_fee:{
        m:0,y:0,
        staff_emolument:{
            m:0,y:0,
            emolument:{m:0,y:0},
            service_fee:{m:0,y:0},
            emolument_extra:{
                welfare:{
                    m:0,y:0,
                    moneyness:{m:0,y:0},
                    non_moneyness:{
                        m:0,y:0,
                        using_right_property_depreciation:{m:0,y:0},
                        depreciation:{m:0,y:0},
                        rent:{m:0,y:0}
                    }
                },
                house_fund:{m:0,y:0},
                social_insurance:{
                    m:0,y:0,
                    enterprise_year_fund:{m:0,y:0},
                },
                union_fund:{m:0,y:0},
                staff_education:{m:0,y:0},
                work_protect:{m:0,y:0},
                other:{m:0,y:0}
            },
            dismiss_welfare:{m:0,y:0},
        },
        depreciation:{m:0,y:0},
        intangible_assets_amortize:{
            m:0,y:0,
            land_using_right:{m:0,y:0},
            softwore:{m:0,y:0}
        },
        fix_cost:{
            m:0,y:0,
            house_fix:{m:0,y:0},
            car_fix:{m:0,y:0},
            equipment_fix:{m:0,y:0},
        },
        low_value_depreciation_amortize:{m:0,y:0},
        officail_work:{m:0,y:0},
        trip_fee:{m:0,y:0},
        business_service_fee:{m:0,y:0},
        afforest_sanitation:{m:0,y:0},
        rent:{
            m:0,y:0,
            house_rent:{m:0,y:0},
            car_rent:{m:0,y:0}
        },
        tenement_manage_cost:{m:0,y:0},
        water_fee:{m:0,y:0},
        electric_fee:{m:0,y:0},
        warm_fee:{m:0,y:0},
        car_drive:{m:0,y:0},
        property_insurance:{m:0,y:0},
        post_communicate:{m:0,y:0},
        meeting:{m:0,y:0},
        guard:{m:0,y:0},
        party_group_activity:{m:0,y:0},
        traffic:{m:0,y:0},
        using_right_property_depreciation:{
            m:0,y:0,
            house_using_right:{m:0,y:0},
            groud_using_right:{m:0,y:0}
        },
        non_rent_using_fee:{m:0,y:0},
        consult_fee:{m:0,y:0},
        other:{m:0,y:0}
    },
    research_develop_cost:{
        m:0,y:0,
        staff_emolument:{
            emolument:{m:0,y:0},
            welfare:{
                m:0,y:0,
                using_right_property_depreciation:{m:0,y:0},
            },
            insurance:{
                m:0,y:0,
                enterprise_year_fund:{m:0,y:0},
            },
            service_fee:{m:0,y:0},
        },
        power:{m:0,y:0},
        low_value_depreciation_amortize:{m:0,y:0},
        fix_cost:{m:0,y:0},
        depreciation:{m:0,y:0},
        using_right_property_depreciation:{m:0,y:0},
        rent:{m:0,y:0},
        intangible_assets_amortize:{m:0,y:0},
        entrust_cooperate_fee:{m:0,y:0},
        new_production_design:{m:0,y:0},
        experiment_try:{m:0,y:0},
        trip_fee:{m:0,y:0},
        meeting:{m:0,y:0},
        other:{m:0,y:0}
    },
    finance_cost:{
        m:0,y:0,
        interest_income:{m:0,y:0},
        interest_disburse:{m:0,y:0},
        bank_handle:{m:0,y:0},
        rent_financing_cost:{m:0,y:0},
        exchange_gain_or_loss:{m:0,y:0},
        other:{m:0,y:0}
    },
    property_decrease_loss:{
        m:0,y:0,
        prepayment:{m:0,y:0},
        inventory:{m:0,y:0},
        long_time_stock_rights:{m:0,y:0},
        fixed_asserts:{m:0,y:0},
        intangible_assets:{m:0,y:0},
        building_project:{m:0,y:0},
        project_material:{m:0,y:0},
        other:{m:0,y:0}
    },
    credit_decrease_loss:{
        m:0,y:0,
        receivables:{m:0,y:0},
        other_receivables:{m:0,y:0},
        creditor_right_investment:{m:0,y:0},
        other:{m:0,y:0}
    },
    fair_value_change:{m:0,y:0},
    investment_gain:{
        m:0,y:0,
        bank_money_manage_gain:{m:0,y:0}
    },
    property_dispose_gain:{
        m:0,y:0,
        non_current_assets_dispose_gain:{
            m:0,y:0,
            fixed_dispose_assets_gain:{m:0,y:0}
        },
    },
    other_gain:{m:0,y:0},
    business_profit:{m:0,y:0},
    business_out_profit:{
        m:0,y:0,
        non_current_assets_dispose_gain:{
            m:0,y:0,
            dispose_fixed_assets_gain:{m:0,y:0}
        },
        government_subsidy:{m:0,y:0}
    },
    business_out_cost:{
        m:0,y:0,
        non_current_assets_dispose_loss:{
            m:0,y:0,
            dispose_fixed_assets_loss:{m:0,y:0}
        },
        fixed_asserts_loss:{m:0,y:0}
    },
    profit_total:{m:0,y:0},
    income_tax_fee:{m:0,y:0},
    retained_profits:{m:0,y:0},
    minority_stockholder_gain:{m:0,y:0},
    retained_profits_belong_to_parent_company:{m:0,y:0},
    supplement_target:{
        m:0,y:0,
        value_add:{m:0,y:0},
        take_back_canceled_bill:{m:0,y:0},
        business_out_cost_abnormal_cost_belong_to_fixed_asset:{m:0,y:0}
    }
}
function read(f){
    data.author = f.A3.v
    data.time = f.H3.v
    var f1 = data.business_income
    console.log(f)
    console.log(f1)
    f1.m = f.E5.v
    f1.y = f.F5.v
    f1.main.m=f.E6.v
    f1.main.y=f.F6.v
    f1.other.m=f.E7.v
    f1.other.y=f.F7.v
    var f2 = data.business_cost
    console.log(f2)
    f2.m = f.E8.v
    f2.y = f.E8.v
    f2.main.m=f.E9.v
    f2.main.y=f.F9.v
    f2.main.staff_emolument.m=f.E10.v
    f2.main.staff_emolument.y=f.F10.v
    f2.main.staff_emolument.emolument.m=f.E11.v
    f2.main.staff_emolument.emolument.y=f.F11.v
    f2.main.staff_emolument.service_fee.m=f.E12.v
    f2.main.staff_emolument.service_fee.y=f.F12.v
    f2.main.staff_emolument.emolument_extra.m=f.E13.v
    f2.main.staff_emolument.emolument_extra.y=f.F13.v
    f2.main.staff_emolument.emolument_extra.welfare.m=f.E14.v
    f2.main.staff_emolument.emolument_extra.welfare.y=f.F14.v
    f2.main.staff_emolument.emolument_extra.welfare.moneyness.m=f.E15.v
    f2.main.staff_emolument.emolument_extra.welfare.moneyness.y=f.F15.v
    f2.main.staff_emolument.emolument_extra.welfare.non_moneyness.m=f.E16.v
    f2.main.staff_emolument.emolument_extra.welfare.non_moneyness.y=f.F16.v
    f2.main.staff_emolument.emolument_extra.welfare.non_moneyness.using_right_property_depreciation.m=f.E17.v
    f2.main.staff_emolument.emolument_extra.welfare.non_moneyness.using_right_property_depreciation.y=f.F17.v
    f2.main.staff_emolument.emolument_extra.welfare.non_moneyness.depreciation.m=f.E18.v
    f2.main.staff_emolument.emolument_extra.welfare.non_moneyness.depreciation.y=f.F18.v
    f2.main.staff_emolument.emolument_extra.welfare.non_moneyness.rent.m=f.E19.v
    f2.main.staff_emolument.emolument_extra.welfare.non_moneyness.rent.y=f.F19.v
    f2.main.staff_emolument.emolument_extra.house_fund.m=f.E20.v
    f2.main.staff_emolument.emolument_extra.house_fund.y=f.F20.v
    f2.main.staff_emolument.emolument_extra.social_insurance.m=f.E21.v
    f2.main.staff_emolument.emolument_extra.social_insurance.y=f.F21.v
    f2.main.staff_emolument.emolument_extra.social_insurance.enterprise_year_fund.m=f.E22.v
    f2.main.staff_emolument.emolument_extra.social_insurance.enterprise_year_fund.y=f.F22.v
    f2.main.staff_emolument.emolument_extra.union_fund.m=f.E23.v
    f2.main.staff_emolument.emolument_extra.union_fund.y=f.F23.v
    f2.main.staff_emolument.emolument_extra.staff_education.m=f.E24.v
    f2.main.staff_emolument.emolument_extra.staff_education.y=f.F24.v
    f2.main.staff_emolument.emolument_extra.work_protect.m=f.E25.v
    f2.main.staff_emolument.emolument_extra.work_protect.y=f.F25.v
    f2.main.staff_emolument.emolument_extra.other.m=f.E26.v
    f2.main.staff_emolument.emolument_extra.other.y=f.F26.v
    f2.main.depreciation.m=f.E27.v
    f2.main.depreciation.y=f.F27.v
    f2.main.fix_cost.m=f.E28.v
    f2.main.fix_cost.y=f.F28.v
    f2.main.fix_cost.house_fix.m=f.E29.v
    f2.main.fix_cost.house_fix.y=f.F29.v
    f2.main.fix_cost.car_fix.m=f.E30.v
    f2.main.fix_cost.car_fix.y=f.F30.v
    f2.main.fix_cost.equipment_fix.m=f.E31.v
    f2.main.fix_cost.equipment_fix.y=f.F31.v
    f2.main.fix_cost.other_fix.m=f.E32.v
    f2.main.fix_cost.other_fix.y=f.F32.v
    f2.main.low_value_depreciation_amortize.m=f.E33.v
    f2.main.low_value_depreciation_amortize.y=f.F33.v
    f2.main.low_value_depreciation_amortize.instrument.m=f.E34.v
    f2.main.low_value_depreciation_amortize.instrument.y=f.F34.v
    f2.main.circuit_network_rent.m=f.E35.v
    f2.main.circuit_network_rent.y=f.F35.v
    f2.main.circuit_network_rent.circuit_rent.m=f.E36.v
    f2.main.circuit_network_rent.circuit_rent.y=f.F36.v
    f2.main.circuit_network_rent.network_rent.m=f.E37.v
    f2.main.circuit_network_rent.network_rent.y=f.F37.v
    f2.main.circuit_network_rent.other.m=f.E38.v
    f2.main.circuit_network_rent.other.y=f.F38.v
    f2.main.water_electric_warm.m=f.E39.v
    f2.main.water_electric_warm.y=f.F39.v
    f2.main.power.m=f.E40.v
    f2.main.power.y=f.F40.v
    f2.main.business_articles.m=f.E41.v
    f2.main.business_articles.y=f.F41.v
    f2.main.car_drive.m=f.E42.v
    f2.main.car_drive.y=f.F42.v
    f2.main.post_communicate.m=f.E43.v
    f2.main.post_communicate.y=f.F43.v
    f2.main.insurance.m=f.E44.v
    f2.main.insurance.y=f.F44.v
    f2.main.trip_fee.m=f.E45.v
    f2.main.trip_fee.y=f.F45.v
    f2.main.book_document_fee.m=f.E46.v
    f2.main.book_document_fee.y=f.F46.v
    f2.main.tenement_manage_cost.m=f.E47.v
    f2.main.tenement_manage_cost.y=f.F47.v
    f2.main.officail_work.m=f.E48.v
    f2.main.officail_work.y=f.F48.v
    f2.main.meeting.m=f.E49.v
    f2.main.meeting.y=f.F49.v
    f2.main.business_outsourcing.m=f.E50.v
    f2.main.business_outsourcing.y=f.F50.v
    f2.main.safety_protect.m=f.E51.v
    f2.main.safety_protect.y=f.F51.v
    f2.main.traffic.m=f.E52.v
    f2.main.traffic.y=f.F52.v
    f2.main.system_integration.m=f.E53.v
    f2.main.system_integration.y=f.F53.v
    f2.main.rent.m=f.E54.v
    f2.main.rent.y=f.F54.v
    f2.main.rent.house_rent.m=f.E55.v
    f2.main.rent.house_rent.y=f.F55.v
    f2.main.rent.car_rent.m=f.E56.v
    f2.main.rent.car_rent.y=f.F56.v
    f2.main.material.m=f.E57.v
    f2.main.material.y=f.F57.v
    f2.main.business_technology_support.m=f.E58.v
    f2.main.business_technology_support.y=f.F58.v
    f2.main.intangible_assets_amortize.m=f.E59.v
    f2.main.intangible_assets_amortize.y=f.F59.v
    f2.main.intangible_assets_amortize.land_using_right.m=f.E60.v
    f2.main.intangible_assets_amortize.land_using_right.y=f.F60.v
    f2.main.service_outsourcing.m=f.E61.v
    f2.main.service_outsourcing.y=f.F61.v
    f2.main.in_network_settle_account_fee.m=f.E62.v
    f2.main.in_network_settle_account_fee.y=f.F62.v
    f2.main.between_network_settle_account_fee.m=f.E63.v
    f2.main.between_network_settle_account_fee.y=f.F63.v
    f2.main.resource_using.m=f.E64.v
    f2.main.resource_using.y=f.F64.v
    f2.main.TCT_fee.m=f.E65.v
    f2.main.TCT_fee.y=f.F65.v
    f2.main.safety_product_fee.m=f.E66.v
    f2.main.safety_product_fee.y=f.F66.v
    f2.main.using_right_property_depreciation.m=f.E67.v
    f2.main.using_right_property_depreciation.y=f.F67.v
    f2.main.using_right_property_depreciation.house_using_right.m=f.E68.v
    f2.main.using_right_property_depreciation.house_using_right.y=f.F68.v
    f2.main.using_right_property_depreciation.groud_using_right.m=f.E69.v
    f2.main.using_right_property_depreciation.groud_using_right.y=f.F69.v
    f2.main.non_rent_using_fee.m=f.E70.v
    f2.main.non_rent_using_fee.y=f.F70.v
    f2.main.non_rent_using_fee.groud_service.m=f.E71.v
    f2.main.non_rent_using_fee.groud_service.y=f.F71.v
    f2.main.non_rent_using_fee.car_service.m=f.E72.v
    f2.main.non_rent_using_fee.car_service.y=f.F72.v
    f2.main.non_rent_using_fee.equipment_service.m=f.E73.v
    f2.main.non_rent_using_fee.equipment_service.y=f.F73.v
    f2.main.non_rent_using_fee.other_service.m=f.E74.v
    f2.main.non_rent_using_fee.other_service.y=f.F74.v
    f2.main.circuit_network_service.m=f.E75.v
    f2.main.circuit_network_service.y=f.F75.v
    f2.main.other.m=f.E76.v
    f2.main.other.y=f.F76.v
    f2.other.m=f.E77.v
    f2.other.y=f.F77.v
    f2.other.staff_emolument.m=f.E78.v
    f2.other.staff_emolument.y=f.F78.v
    f2.other.staff_emolument.emolument.m=f.E79.v
    f2.other.staff_emolument.emolument.y=f.F79.v
    f2.other.staff_emolument.service_fee.m=f.E80.v
    f2.other.staff_emolument.service_fee.y=f.F80.v
    f2.other.staff_emolument.emolument_extra.m=f.E81.v
    f2.other.staff_emolument.emolument_extra.y=f.F81.v
    f2.other.staff_emolument.emolument_extra.welfare.m=f.E82.v
    f2.other.staff_emolument.emolument_extra.welfare.y=f.F82.v
    f2.other.staff_emolument.emolument_extra.welfare.moneyness.m=f.E83.v
    f2.other.staff_emolument.emolument_extra.welfare.moneyness.y=f.F83.v
    f2.other.staff_emolument.emolument_extra.welfare.non_moneyness.m=f.E84.v
    f2.other.staff_emolument.emolument_extra.welfare.non_moneyness.y=f.F84.v
    f2.other.staff_emolument.emolument_extra.welfare.non_moneyness.using_right_property_depreciation.m=f.E85.v
    f2.other.staff_emolument.emolument_extra.welfare.non_moneyness.using_right_property_depreciation.y=f.F85.v
    f2.other.staff_emolument.emolument_extra.welfare.non_moneyness.depreciation.m=f.E86.v
    f2.other.staff_emolument.emolument_extra.welfare.non_moneyness.depreciation.y=f.F86.v
    f2.other.staff_emolument.emolument_extra.welfare.non_moneyness.rent.m=f.E87.v
    f2.other.staff_emolument.emolument_extra.welfare.non_moneyness.rent.y=f.F87.v
    f2.other.staff_emolument.emolument_extra.house_fund.m=f.E88.v
    f2.other.staff_emolument.emolument_extra.house_fund.y=f.F88.v
    f2.other.staff_emolument.emolument_extra.social_insurance.m=f.E89.v
    f2.other.staff_emolument.emolument_extra.social_insurance.y=f.F89.v
    f2.other.staff_emolument.emolument_extra.staff_education.m=f.E90.v
    f2.other.staff_emolument.emolument_extra.staff_education.y=f.F90.v
    f2.other.staff_emolument.emolument_extra.union_fund.m=f.E91.v
    f2.other.staff_emolument.emolument_extra.union_fund.y=f.F91.v
    f2.other.staff_emolument.emolument_extra.work_protect.m=f.E92.v
    f2.other.staff_emolument.emolument_extra.work_protect.y=f.F92.v
    f2.other.staff_emolument.emolument_extra.other.m=f.E93.v
    f2.other.staff_emolument.emolument_extra.other.y=f.F93.v
    f2.other.depreciation.m=f.E94.v
    f2.other.depreciation.y=f.F94.v
    f2.other.sell_terminal_commodity.m=f.E95.v
    f2.other.sell_terminal_commodity.y=f.F95.v
    f2.other.sell_terminal_commodity.cellphone.m=f.E96.v
    f2.other.sell_terminal_commodity.cellphone.y=f.F96.v
    f2.other.sell_equipment.m=f.E97.v
    f2.other.sell_equipment.y=f.F97.v
    f2.other.rent_business_cost.m=f.E98.v
    f2.other.rent_business_cost.y=f.F98.v
    f2.other.rent_business_cost.using_right_property_depreciation.m=f.E99.v
    f2.other.rent_business_cost.using_right_property_depreciation.y=f.F99.v
    f2.other.softwore_service_cost.m=f.E100.v
    f2.other.softwore_service_cost.y=f.F100.v
    f2.other.tenement_manage_cost.m=f.E101.v
    f2.other.tenement_manage_cost.y=f.F101.v
    f2.other.physica_distribution_service.m=f.E102.v
    f2.other.physica_distribution_service.y=f.F102.v
    f2.other.other.m=f.E103.v
    f2.other.other.y=f.F103.v
    var f3 = data.tax_and_extra
    f3.m=f.E104.v
    f3.y=f.F104.v
    var f4 = data.sell_fee
    f4.m=f.E105.v
    f4.y=f.F105.v
    f4.exhibition_fee.m=f.E106.v
    f4.exhibition_fee.y=f.F106.v
    f4.advertisement_fee.m=f.E107.v
    f4.advertisement_fee.y=f.F107.v
    f4.business_publicity.m=f.E108.v
    f4.business_publicity.y=f.F108.v
    f4.promotion_fee.m=f.E109.v
    f4.promotion_fee.y=f.F109.v
    f4.social_channel_handle_fee.m=f.E110.v
    f4.social_channel_handle_fee.y=f.F110.v
    f4.social_channel_service_fee.m=f.E111.v
    f4.social_channel_service_fee.y=f.F111.v
    f4.market_outsourcing_fee.m=f.E112.v
    f4.market_outsourcing_fee.y=f.F112.v
    f4.arreara_urge_fee.m=f.E113.v
    f4.arreara_urge_fee.y=f.F113.v
    f4.custommer_service.m=f.E114.v
    f4.custommer_service.y=f.F114.v
    var f5=data.manage_fee
    f5.m=f.E115.v
    f5.y=f.F115.v
    f5.staff_emolument.m=f.E116.v
    f5.staff_emolument.y=f.F116.v
    f5.staff_emolument.emolument.m=f.E117.v
    f5.staff_emolument.emolument.y=f.F117.v
    f5.staff_emolument.service_fee.m=f.E118.v
    f5.staff_emolument.service_fee.y=f.F118.v
    f5.staff_emolument.emolument_extra.m=f.E119.v
    f5.staff_emolument.emolument_extra.y=f.F119.v
    f5.staff_emolument.emolument_extra.welfare.m=f.L5.v
    f5.staff_emolument.emolument_extra.welfare.y=f.M5.v
    f5.staff_emolument.emolument_extra.welfare.moneyness.m=f.L6.v
    f5.staff_emolument.emolument_extra.welfare.moneyness.y=f.M6.v
    f5.staff_emolument.emolument_extra.welfare.non_moneyness.m=f.L7.v
    f5.staff_emolument.emolument_extra.welfare.non_moneyness.y=f.M7.v
    f5.staff_emolument.emolument_extra.welfare.non_moneyness.using_right_property_depreciation.m=f.L8.v
    f5.staff_emolument.emolument_extra.welfare.non_moneyness.using_right_property_depreciation.y=f.M8.v
    f5.staff_emolument.emolument_extra.welfare.non_moneyness.depreciation.m=f.L9.v
    f5.staff_emolument.emolument_extra.welfare.non_moneyness.depreciation.y=f.M9.v
    f5.staff_emolument.emolument_extra.welfare.non_moneyness.rent.m=f.L10.v
    f5.staff_emolument.emolument_extra.welfare.non_moneyness.rent.y=f.M10.v
    f5.staff_emolument.emolument_extra.house_fund.m=f.L11.v
    f5.staff_emolument.emolument_extra.house_fund.y=f.M11.v
    f5.staff_emolument.emolument_extra.social_insurance.m=f.L12.v
    f5.staff_emolument.emolument_extra.social_insurance.y=f.M12.v
    f5.staff_emolument.emolument_extra.social_insurance.enterprise_year_fund.m=f.L13.v
    f5.staff_emolument.emolument_extra.social_insurance.enterprise_year_fund.y=f.M13.v
    f5.staff_emolument.emolument_extra.union_fund.m=f.L14.v
    f5.staff_emolument.emolument_extra.union_fund.y=f.M14.v
    f5.staff_emolument.emolument_extra.staff_education.m=f.L15.v
    f5.staff_emolument.emolument_extra.staff_education.y=f.M15.v
    f5.staff_emolument.emolument_extra.work_protect.m=f.L16.v
    f5.staff_emolument.emolument_extra.work_protect.y=f.M16.v
    f5.staff_emolument.emolument_extra.other.m=f.L17.v
    f5.staff_emolument.emolument_extra.other.y=f.M17.v
    f5.staff_emolument.dismiss_welfare.m=f.L18.v
    f5.staff_emolument.dismiss_welfare.y=f.M18.v
    f5.depreciation.m=f.L19.v
    f5.depreciation.y=f.M19.v
    f5.intangible_assets_amortize.m=f.L20.v
    f5.intangible_assets_amortize.y=f.M20.v
    f5.intangible_assets_amortize.land_using_right.m=f.L21.v
    f5.intangible_assets_amortize.land_using_right.y=f.M21.v
    f5.intangible_assets_amortize.softwore.m=f.L22.v
    f5.intangible_assets_amortize.softwore.y=f.M22.v
    f5.fix_cost.m=f.L23.v
    f5.fix_cost.y=f.M23.v
    f5.fix_cost.house_fix.m=f.L24.v
    f5.fix_cost.house_fix.y=f.M24.v
    f5.fix_cost.car_fix.m=f.L25.v
    f5.fix_cost.car_fix.y=f.M25.v
    f5.fix_cost.equipment_fix.m=f.L26.v
    f5.fix_cost.equipment_fix.y=f.M26.v
    f5.low_value_depreciation_amortize.m=f.L27.v
    f5.low_value_depreciation_amortize.y=f.M7.v
    f5.officail_work.m=f.L28.v
    f5.officail_work.y=f.M28.v
    f5.trip_fee.m=f.L29.v
    f5.trip_fee.y=f.M29.v
    f5.business_service_fee.m=f.L30.v
    f5.business_service_fee.y=f.M30.v
    f5.afforest_sanitation.m=f.L31.v
    f5.afforest_sanitation.y=f.M31.v
    f5.rent.m=f.L32.v
    f5.rent.y=f.M32.v
    f5.rent.house_rent.m=f.L33.v
    f5.rent.house_rent.y=f.M33.v
    f5.rent.car_rent.m=f.L34.v
    f5.rent.car_rent.y=f.M34.v
    f5.tenement_manage_cost.m=f.L35.v
    f5.tenement_manage_cost.y=f.M35.v
    f5.water_fee.m=f.L36.v
    f5.water_fee.y=f.M36.v
    f5.electric_fee.m=f.L37.v
    f5.electric_fee.y=f.M37.v
    f5.warm_fee.m=f.L38.v
    f5.warm_fee.y=f.M38.v
    f5.car_drive.m=f.L39.v
    f5.car_drive.y=f.M39.v
    f5.property_insurance.m=f.L40.v
    f5.property_insurance.y=f.M40.v
    f5.post_communicate.m=f.L41.v
    f5.post_communicate.y=f.M41.v
    f5.meeting.m=f.L42.v
    f5.meeting.y=f.M42.v
    f5.guard.m=f.L43.v
    f5.guard.y=f.M43.v
    f5.party_group_activity.m=f.L44.v
    f5.party_group_activity.y=f.M44.v
    f5.traffic.m=f.L45.v
    f5.traffic.y=f.M45.v
    f5.using_right_property_depreciation.m=f.L46.v
    f5.using_right_property_depreciation.y=f.M46.v
    f5.using_right_property_depreciation.house_using_right.m=f.L47.v
    f5.using_right_property_depreciation.house_using_right.y=f.M47.v
    f5.using_right_property_depreciation.groud_using_right.m=f.L48.v
    f5.using_right_property_depreciation.groud_using_right.y=f.M48.v
    f5.non_rent_using_fee.m=f.L49.v
    f5.non_rent_using_fee.y=f.M49.v
    f5.consult_fee.m=f.L50.v
    f5.consult_fee.y=f.M50.v
    f5.other.m=f.L51.v
    f5.other.y=f.M51.v
    var f6 = data.research_develop_cost
    f6.m=f.L52.v
    f6.y=f.M52.v
    f6.staff_emolument.m=f.L53.v
    f6.staff_emolument.y=f.M53.v
    f6.staff_emolument.emolument.m=f.L54.v
    f6.staff_emolument.emolument.y=f.M54.v
    f6.staff_emolument.welfare.m=f.L55.v
    f6.staff_emolument.welfare.y=f.M55.v
    f6.staff_emolument.welfare.using_right_property_depreciation.m=f.L56.v
    f6.staff_emolument.welfare.using_right_property_depreciation.y=f.M56.v
    f6.staff_emolument.insurance.m=f.L57.v
    f6.staff_emolument.insurance.y=f.M57.v
    f6.staff_emolument.insurance.enterprise_year_fund.m=f.L58.v
    f6.staff_emolument.insurance.enterprise_year_fund.y=f.M58.v
    f6.staff_emolument.service_fee.m=f.L59.v
    f6.staff_emolument.service_fee.y=f.M59.v
    f6.power.m=f.L60.v
    f6.power.y=f.M60.v
    f6.low_value_depreciation_amortize.m=f.L61.v
    f6.low_value_depreciation_amortize.y=f.M61.v
    f6.fix_cost.m=f.L62.v
    f6.fix_cost.y=f.M62.v
    f6.depreciation.m=f.L63.v
    f6.depreciation.y=f.M63.v
    f6.using_right_property_depreciation.m=f.L64.v
    f6.using_right_property_depreciation.y=f.M64.v
    f6.rent.m=f.L65.v
    f6.rent.y=f.M65.v
    f6.intangible_assets_amortize.m=f.L66.v
    f6.intangible_assets_amortize.y=f.M66.v
    f6.entrust_cooperate_fee.m=f.L67.v
    f6.entrust_cooperate_fee.y=f.M67.v
    f6.new_production_design.m=f.L68.v
    f6.new_production_design.y=f.M68.v
    f6.experiment_try.m=f.L69.v
    f6.experiment_try.y=f.M69.v
    f6.trip_fee.m=f.L70.v
    f6.trip_fee.y=f.M70.v
    f6.meeting.m=f.L71.v
    f6.meeting.y=f.M71.v
    f6.other.m=f.L72.v
    f6.other.y=f.M72.v
    var f7 = data.finance_cost
    f7.m=f.L73.v
    f7.y=f.M73.v
    f7.interest_income.m=f.L74.v
    f7.interest_income.y=f.M74.v
    f7.interest_disburse.m=f.L75.v
    f7.interest_disburse.y=f.M75.v
    f7.bank_handle.m=f.L76.v
    f7.bank_handle.y=f.M76.v
    f7.rent_financing_cost.m=f.L77.v
    f7.rent_financing_cost.y=f.M77.v
    f7.exchange_gain_or_loss.m=f.L78.v
    f7.exchange_gain_or_loss.y=f.M78.v
    f7.other.m=f.L79.v
    f7.other.y=f.M79.v
    var f8 = data.property_decrease_loss
    f8.m=f.L80.v
    f8.y=f.M80.v
    f8.prepayment.m=f.L81.v
    f8.prepayment.y=f.M81.v
    f8.inventory.m=f.L82.v
    f8.inventory.y=f.M82.v
    f8.long_time_stock_rights.m=f.L83.v
    f8.long_time_stock_rights.y=f.M83.v
    f8.fixed_asserts.m=f.L84.v
    f8.fixed_asserts.y=f.M84.v
    f8.intangible_assets.m=f.L85.v
    f8.intangible_assets.y=f.M85.v
    f8.building_project.m=f.L86.v
    f8.building_project.y=f.M86.v
    f8.project_material.m=f.L87.v
    f8.project_material.y=f.M87.v
    f8.other.m=f.L88.v
    f8.other.y=f.M88.v
    var f9 = data.credit_decrease_loss
    f9.m=f.L89.v
    f9.y=f.M89.v
    f9.receivables.m=f.L90.v
    f9.receivables.y=f.M90.v
    f9.other_receivables.m=f.L91.v
    f9.other_receivables.y=f.M91.v
    f9.creditor_right_investment.m=f.L92.v
    f9.creditor_right_investment.y=f.M92.v
    f9.other.m=f.L93.v
    f9.other.y=f.M93.v
    var f10 = data.fair_value_change
    f10.m=f.L94.v
    f10.y=f.M94.v
    var f11 = data.investment_gain
    f11.m=f.L95.v
    f11.y=f.M95.v
    f11.bank_money_manage_gain.m=f.L96.v
    f11.bank_money_manage_gain.y=f.M96.v
    var f12 = data.property_dispose_gain
    f12.m=f.L97.v
    f12.y=f.M97.v
    f12.non_current_assets_dispose_gain.m=f.L98.v
    f12.non_current_assets_dispose_gain.y=f.M98.v
    f12.non_current_assets_dispose_gain.fixed_dispose_assets_gain.m=f.L99.v
    f12.non_current_assets_dispose_gain.fixed_dispose_assets_gain.y=f.M99.v
    var f13 = data.other_gain
    f13.m=f.L100.v
    f13.y=f.M100.v
    var f14 = data.business_profit
    f14.m=f.L101.v
    f14.y=f.M101.v
    var f15 = data.business_out_profit
    f15.m=f.L102.v
    f15.y=f.M102.v
    f15.non_current_assets_dispose_gain.m=f.L103.v
    f15.non_current_assets_dispose_gain.y=f.M103.v
    f15.non_current_assets_dispose_gain.dispose_fixed_assets_gain.m=f.L104.v
    f15.non_current_assets_dispose_gain.dispose_fixed_assets_gain.y=f.M104.v
    f15.government_subsidy.m=f.L105.v
    f15.government_subsidy.y=f.M105.v
    var f16 = data.business_out_cost
    f16.m=f.L106.v
    f16.y=f.M106.v
    f16.non_current_assets_dispose_loss.m=f.L107.v
    f16.non_current_assets_dispose_loss.y=f.M107.v
    f16.non_current_assets_dispose_loss.dispose_fixed_assets_loss.m=f.L108.v
    f16.non_current_assets_dispose_loss.dispose_fixed_assets_loss.y=f.M108.v
    f16.fixed_asserts_loss.m=f.L109.v
    f16.fixed_asserts_loss.y=f.M109.v
    var f17 = data.profit_total
    f17.m=f.L110.v
    f17.y=f.M110.v
    var f18 = data.income_tax_fee
    f18.m=f.L111.v
    f18.y=f.M111.v
    var f19 = data.retained_profits
    f19.m=f.L112.v
    f19.y=f.M112.v
    var f20 = data.minority_stockholder_gain
    f20.m=f.L113.v
    f20.y=f.M113.v
    var f21 = data.retained_profits_belong_to_parent_company
    f21.m=f.L114.v
    f21.y=f.M114.v
    var f22 = data.supplement_target
    f22.m=f.L115.v
    f22.y=f.M115.v
    f22.value_add.m=f.L116.v
    f22.value_add.y=f.M116.v
    f22.take_back_canceled_bill.m=f.L117.v
    f22.take_back_canceled_bill.y=f.M117.v
    f22.business_out_cost_abnormal_cost_belong_to_fixed_asset.m=f.L118.v
    f22.business_out_cost_abnormal_cost_belong_to_fixed_asset.y=f.M118.v
    console.log(data)
    return data
}
export {read}