var data={
    author:"",
    time:"",
    business:[],//x轴
}
var project={
    business_type:"",
    income:{
        name:"收入",
        business_income:{value:1,name:"一、收入"}
    },
    cost:{
        name:"支出",
        total_cost:{
            value:0,name:"二、成本费用支出",
            business_cost:{
                value:0,name:"（一）营业成本",
                staff_emolument:{
                    value:0,name:"1、职工薪酬",
                    emolument:{value:0,name:"其中：工资"},
                    emolument_extra:{value:0,name:"工资附加费"},
                    service_fee:{value:0,name:"劳务费"}
                },
                depreciation:{value:0,name:"2、折旧费"},
                fix_cost:{value:0,name:"3、维修费"},
                low_value_depreciation_amortize:{
                    value:0,name:"4、低值易耗品摊销",
                    instrument:{value:0,name:"其中：仪器仪表摊销(核算口径）"}
                },
                water_electric_warm:{value:0,name:"5、水电取暖费"},
                power:{value:0,name:"6、动力费"},
                business_articles:{value:0,name:"7、业务用品费"},
                car_drive:{value:0,name:"8、车辆运行费"},
                post_communicate:{value:0,name:"9、邮寄通信运杂费"},
                insurance:{value:0,name:"10、保险费"},
                trip_fee:{value:0,name:"11、差旅费"},
                book_document_fee:{value:0,name:"12、图书资料费"},
                tenement_manage_cost:{value:0,name:"13、物业管理费"},
                officail_work:{value:0,name:"14、办公费"},
                meeting:{value:0,name:"15、会议费"},
                business_outsourcing:{value:0,name:"16、业务外包费"},
                safety_protect:{value:0,name:"17、安全保护费"},
                traffic:{value:0,name:"18、交通费"},
                rent:{
                    value:0,name:"19、租赁费",
                    house_rent:{value:0,name:"其中：房屋租赁费"},
                    car_rent:{value:0,name:"车辆租赁费"}
                },
                material:{value:0,name:"20、材料费"},
                business_technology_support:{value:0,name:"21、业务技术支撑费"},
                circuit_network_rent:{value:0,name:"22、电路及网元租赁费"},
                service_outsourcing:{value:0,name:"23、客服外包费"},
                in_network_settle_account_fee:{value:0,name:"24、网内结算"},
                between_network_settle_account_fee:{value:0,name:"25、网间结算"},
                resource_using:{value:0,name:"26、资源占用费"},
                TCT:{value:0,name:"27、ICT业务成本"},
                circuit_network_service:{value:0,name:"28、电路及网元服务费"},
                using_right_property_depreciation:{
                    value:0,name:"29、使用权资产折旧费",
                    house_using_right:{value:0,name:"其中：房屋使用权资产折旧费"},
                    groud_using_right:{value:0,name:"场地使用权资产折旧"},
                },
                non_rent_using_fee:{
                    value:0,name:"30、非租赁使用费",
                    groud_service:{value:0,name:"其中：场地服务"},
                    car_service:{value:0,name:"车辆服务"},
                },
                other:{
                    value:0,name:"31、其他",
                    tax_and_extra:{value:0,name:"（二）税金及附加"},
                    sell_cost:{value:0,name:"（三）销售费用"},
                    manage_cost:{
                        value:0,name:"（四）管理费用",
                        staff_emolument:{
                            value:0,name:"其中：1、职工薪酬",
                            emolument:{value:0,name:"其中：工资"},
                            emolument_extra:{value:0,name:"工资附加费"},
                            service_fee:{value:0,name:"劳务费"}
                        },
                        depreciation:{value:0,name:"2、折旧费"},
                    },

                }
            }
        },
    },
    profit:{
        name:"利润",
        business_profit:{value:0,name:"三、营业利润"}
    }
    }
var list=['D','E','F','G','H','I','J','K','L','M','N','O']
import {set} from './set'
function read_market_gain_loss_bus(f){
    data.author=f.A3.v
    data.time=f.G3.v
    data.business = []
    for(let i of list){
        console.log(i)
        let temp=JSON.parse(JSON.stringify(project))
        if(f[i+'5'])
            temp.business_type=f[i+'5'].v
        else{
            temp.business_type=f[i+'4'].v   
        }
        temp.income.business_income.value=set(f,i+'7')
        let t1=temp.cost.total_cost
        t1.value=set(f,i+'8')
        t1.business_cost.value=set(f,i+'9')
        t1.business_cost.staff_emolument.value=set(f,i+'10')
        t1.business_cost.staff_emolument.emolument.value=set(f,i+'11')
        t1.business_cost.staff_emolument.emolument_extra.value=set(f,i+'12')
        t1.business_cost.staff_emolument.service_fee.value=set(f,i+'13')
        t1.business_cost.depreciation.value=set(f,i+'14')
        t1.business_cost.fix_cost.value=set(f,i+'15')
        t1.business_cost.low_value_depreciation_amortize.value=set(f,i+'16')
        t1.business_cost.low_value_depreciation_amortize.instrument.value=set(f,i+'17')
        t1.business_cost.water_electric_warm.value=set(f,i+'18')
        t1.business_cost.power.value=set(f,i+'19')
        t1.business_cost.business_articles.value=set(f,i+'20')
        t1.business_cost.car_drive.value=set(f,i+'21')
        t1.business_cost.post_communicate.value=set(f,i+'22')
        t1.business_cost.insurance.value=set(f,i+'23')
        t1.business_cost.trip_fee.value=set(f,i+'24')
        t1.business_cost.book_document_fee.value=set(f,i+'25')
        t1.business_cost.tenement_manage_cost.value=set(f,i+'26')
        t1.business_cost.officail_work.value=set(f,i+'27')
        t1.business_cost.meeting.value=set(f,i+'28')
        t1.business_cost.business_outsourcing.value=set(f,i+'29')
        t1.business_cost.safety_protect.value=set(f,i+'30')
        t1.business_cost.traffic.value=set(f,i+'31')
        t1.business_cost.rent.value=set(f,i+'32')
        t1.business_cost.rent.house_rent.value=set(f,i+'33')
        t1.business_cost.rent.car_rent.value=set(f,i+'34')
        t1.business_cost.material.value=set(f,i+'35')
        t1.business_cost.business_technology_support.value=set(f,i+'36')
        t1.business_cost.circuit_network_rent.value=set(f,i+'37')
        t1.business_cost.service_outsourcing.value=set(f,i+'38')
        t1.business_cost.in_network_settle_account_fee.value=set(f,i+'39')
        t1.business_cost.between_network_settle_account_fee.value=set(f,i+'40')
        t1.business_cost.resource_using.value=set(f,i+'41')
        t1.business_cost.TCT.value=set(f,i+'42')
        t1.business_cost.circuit_network_service.value=set(f,i+'43')
        t1.business_cost.using_right_property_depreciation.value=set(f,i+'44')
        t1.business_cost.using_right_property_depreciation.house_using_right.value=set(f,i+'45')
        t1.business_cost.using_right_property_depreciation.groud_using_right.value=set(f,i+'46')
        t1.business_cost.non_rent_using_fee.value=set(f,i+'47')
        t1.business_cost.non_rent_using_fee.groud_service.value=set(f,i+'48')
        t1.business_cost.non_rent_using_fee.car_service.value=set(f,i+'49')
        t1.business_cost.other.value=set(f,i+'50')
        t1.business_cost.other.tax_and_extra.value=set(f,i+'51')
        t1.business_cost.other.sell_cost.value=set(f,i+'52')
        t1.business_cost.other.manage_cost.value=set(f,i+'53')
        t1.business_cost.other.manage_cost.staff_emolument.value=set(f,i+'54')
        t1.business_cost.other.manage_cost.staff_emolument.emolument.value=set(f,i+'55')
        t1.business_cost.other.manage_cost.staff_emolument.emolument_extra.value=set(f,i+'56')
        t1.business_cost.other.manage_cost.staff_emolument.service_fee.value=set(f,i+'57')
        t1.business_cost.other.manage_cost.depreciation.value=set(f,i+'58')
        temp.profit.business_profit.value=set(f,i+'59')
        data.business.push(temp)
    }   
    console.log(data)
    return data
}
export {read_market_gain_loss_bus}