var data={
    author:"",
    time:"",
    business_gain_total:{
        m:0,y:0,
        network_manage_technology_service_cost:{
            m:0,y:0,
            family_customer_manage:{
                m:0,y:0,
                open_dubug_service:{m:0,y:0},
                technology_service:{m:0,y:0}
            },
            group_customer_manage:{
                m:0,y:0,
                open_dubug_service:{m:0,y:0},
                technology_service:{m:0,y:0}
            },
            base_station_manage:{m:0,y:0},
            optical_cable_manage:{m:0,y:0},
            WLAN_manage:{m:0,y:0},
            iron_tower_manage:{m:0,y:0},
            IDC_manage:{m:0,y:0},
            network_optimize:{m:0,y:0},
            network_resource_check_and_maintain:{m:0,y:0},
            family_group_network_service:{m:0,y:0},
            intellectual_product_fix:{m:0,y:0},
            room_diliver_manage:{m:0,y:0},
            other_manage:{m:0,y:0}
        },
        project_service:{
            m:0,y:0,
            project:{
                m:0,y:0,
                project_group:{m:0,y:0},
                project_family:{m:0,y:0},
                project_transfer_pipe:{m:0,y:0},
                equipment_install:{m:0,y:0},
                room_diliver:{m:0,y:0},
                WLAN:{m:0,y:0},
                ICT:{m:0,y:0},
                IDC:{m:0,y:0},
                other:{m:0,y:0}
            },
            design_service:{m:0,y:0},
            project_manage:{m:0,y:0},
            project_watch:{m:0,y:0},
            other:{m:0,y:0}
        },
        market_bussiness_service_gain:{
            m:0,y:0,
            sell_service:{
                m:0,y:0,
                family:{m:0,y:0},
                person:{m:0,y:0},
                group:{
                    m:0,y:0,
                    ICT:{m:0,y:0},
                    medium_small_company:{m:0,y:0},
                    infomatization_service:{m:0,y:0}
                },
                intnet_business:{m:0,y:0},
                oprate_service:{m:0,y:0},
                other:{m:0,y:0}
            },
            service_support:{
                m:0,y:0,
                medium_small_company_support:{m:0,y:0},
                group_support:{m:0,y:0},
                ICT:{
                    m:0,y:0,
                    system_integration:{m:0,y:0},
                    maintain_insurance:{m:0,y:0}
                },
                IDC:{m:0,y:0},
                cloud_comput:{m:0,y:0},
                big_data:{m:0,y:0},
                other:{m:0,y:0}
            },
            store_business:{
                m:0,y:0,
                self_user_business:{
                    m:0,y:0,
                    voice:{m:0,y:0},
                    data:{m:0,y:0},
                    resource_rent:{
                        m:0,y:0,
                        cooparate_build:{m:0,y:0}
                    },
                    in_network:{m:0,y:0},
                    between_network:{m:0,y:0},
                    other:{m:0,y:0}
                },
                resource_using_fee:{m:0,y:0},
                user_change_compensation:{m:0,y:0}
            }
        },
        measure_and_network_test_gain:{
            m:0,y:0,
            instrument_measure:{m:0,y:0},
            network_5G_measure:{m:0,y:0},
            wireless_network_measure:{m:0,y:0},
            intnet_measure:{m:0,y:0},
            intnet_of_thing_measure:{m:0,y:0},
            other_measure:{m:0,y:0}
        },
        other_gain:{
            m:0,y:0,
            sell_terminal_and_good:{m:0,y:0},
            sell_equipment:{m:0,y:0},
            rent_business:{m:0,y:0},
            software_service:{m:0,y:0},
            tenement_manage:{m:0,y:0},
            physica_distribution_service:{m:0,y:0},
            other:{m:0,y:0}
        }
    }
}
function read_business_gain(f){
    console.log(f)
    data.author = f.A3.v
    data.time = f.D3.v  
    data.business_gain_total.m = f.C5.v 
    data.business_gain_total.y = f.D5.v
    var f1 = data.business_gain_total.network_manage_technology_service_cost
    // console.log(f1)
    f1.m=f.C6.v
    f1.y=f.D6.v
    f1.family_customer_manage.m=f.C7.v
    f1.family_customer_manage.y=f.D7.v
    f1.family_customer_manage.open_dubug_service.m=f.C8.v
    f1.family_customer_manage.open_dubug_service.y=f.D8.v  
    f1.family_customer_manage.technology_service.m=f.C9.v
    f1.family_customer_manage.technology_service.y=f.D9.v
    f1.group_customer_manage.m=f.C10.v
    f1.group_customer_manage.y=f.D10.v
    f1.group_customer_manage.open_dubug_service.m=f.C11.v
    f1.group_customer_manage.open_dubug_service.y=f.D11.v
    f1.group_customer_manage.technology_service.m=f.C12.v
    f1.group_customer_manage.technology_service.y=f.D12.v
    f1.base_station_manage.m=f.C13.v
    f1.base_station_manage.y=f.D13.v
    f1.optical_cable_manage.m=f.C14.v
    f1.optical_cable_manage.y=f.D14.v
    f1.WLAN_manage.m=f.C15.v
    f1.WLAN_manage.y=f.D15.v
    f1.iron_tower_manage.m=f.C16.v
    f1.iron_tower_manage.y=f.D16.v
    f1.IDC_manage.m=f.C17.v
    f1.IDC_manage.y=f.D17.v
    f1.network_optimize.m=f.C18.v
    f1.network_optimize.y=f.D18.v
    f1.network_resource_check_and_maintain.m=f.C19.v
    f1.network_resource_check_and_maintain.y=f.D19.v
    f1.family_group_network_service.m=f.C20.v
    f1.family_group_network_service.y=f.D20.v
    f1.intellectual_product_fix.m=f.C21.v
    f1.intellectual_product_fix.y=f.D21.v
    f1.room_diliver_manage.m=f.C22.v
    f1.room_diliver_manage.y=f.D22.v
    f1.other_manage.m=f.C23.v
    f1.other_manage.y=f.D23.v
    var f2 = data.business_gain_total.project_service
    // console.log(f2)
    f2.m=f.C24.v
    f2.y=f.D24.v
    f2.project.m=f.C25.v
    f2.project.y=f.D25.v
    f2.project.project_group.m=f.C26.v
    f2.project.project_group.y=f.D26.v
    f2.project.project_family.m=f.C27.v
    f2.project.project_family.y=f.D27.v
    f2.project.project_transfer_pipe.m=f.C28.v
    f2.project.project_transfer_pipe.y=f.D28.v
    f2.project.equipment_install.m=f.C29.v
    f2.project.equipment_install.y=f.D29.v
    f2.project.room_diliver.m=f.C30.v
    f2.project.room_diliver.y=f.D30.v
    f2.project.WLAN.m=f.C31.v
    f2.project.WLAN.y=f.D31.v
    f2.project.ICT.m=f.C32.v
    f2.project.ICT.y=f.D32.v
    f2.project.IDC.m=f.C33.v
    f2.project.IDC.y=f.D33.v
    f2.project.other.m=f.C34.v
    f2.project.other.y=f.D34.v
    f2.design_service.m=f.C35.v
    f2.design_service.y=f.D35.v
    f2.project_manage.m=f.C36.v
    f2.project_manage.y=f.D36.v
    f2.project_watch.m=f.C37.v
    f2.project_watch.y=f.D37.v
    f2.other.m=f.C38.v
    f2.other.y=f.D38.v
    var f3 = data.business_gain_total.market_bussiness_service_gain
    // console.log(f3)
    f3.m=f.C39.v
    f3.y=f.D39.v
    f3.sell_service.m=f.C40.v
    f3.sell_service.y=f.D40.v
    f3.sell_service.family.m=f.C41.v
    f3.sell_service.family.y=f.D41.v
    f3.sell_service.person.m=f.C42.v
    f3.sell_service.person.y=f.D42.v
    f3.sell_service.group.m=f.C43.v
    f3.sell_service.group.y=f.D43.v
    f3.sell_service.group.ICT.m=f.C44.v
    f3.sell_service.group.ICT.y=f.D44.v
    f3.sell_service.group.medium_small_company.m=f.C45.v
    f3.sell_service.group.medium_small_company.y=f.D45.v
    f3.sell_service.group.infomatization_service.m=f.C46.v
    f3.sell_service.group.infomatization_service.y=f.D46.v
    f3.sell_service.intnet_business.m=f.C47.v
    f3.sell_service.intnet_business.y=f.D47.v
    f3.sell_service.oprate_service.m=f.C48.v
    f3.sell_service.oprate_service.y=f.D48.v
    f3.sell_service.other.m=f.C49.v
    f3.sell_service.other.y=f.D49.v
    f3.service_support.m=f.C50.v
    f3.service_support.y=f.D50.v
    f3.service_support.medium_small_company_support.m=f.C51.v
    f3.service_support.medium_small_company_support.y=f.D51.v
    f3.service_support.group_support.m=f.C52.v
    f3.service_support.group_support.y=f.D52.v
    f3.service_support.ICT.m=f.C53.v
    f3.service_support.ICT.y=f.D53.v
    f3.service_support.ICT.system_integration.m=f.C54.v
    f3.service_support.ICT.system_integration.y=f.D54.v
    f3.service_support.ICT.maintain_insurance.m=f.C55.v
    f3.service_support.ICT.maintain_insurance.y=f.D55.v
    f3.service_support.IDC.m=f.C56.v
    f3.service_support.IDC.y=f.D56.v
    f3.service_support.cloud_comput.m=f.C57.v
    f3.service_support.cloud_comput.y=f.D57.v
    f3.service_support.big_data.m=f.C58.v
    f3.service_support.big_data.y=f.D58.v
    f3.service_support.other.m=f.C59.v
    f3.service_support.other.y=f.D59.v
    f3.store_business.m=f.C60.v
    f3.store_business.y=f.D60.v
    f3.store_business.self_user_business.m=(f.C61?f.C61.v:0)
    f3.store_business.self_user_business.y=f.D61.v
    f3.store_business.self_user_business.voice.m=f.C62.v
    f3.store_business.self_user_business.voice.y=f.D62.v
    f3.store_business.self_user_business.data.m=f.C63.v
    f3.store_business.self_user_business.data.y=f.D63.v
    f3.store_business.self_user_business.resource_rent.m=f.C64.v
    f3.store_business.self_user_business.resource_rent.y=f.D64.v
    f3.store_business.self_user_business.resource_rent.cooparate_build.m=f.C65.v
    f3.store_business.self_user_business.resource_rent.cooparate_build.y=f.D65.v
    f3.store_business.self_user_business.in_network.m=f.C66.v
    f3.store_business.self_user_business.in_network.y=f.D66.v
    f3.store_business.self_user_business.between_network.m=f.C67.v
    f3.store_business.self_user_business.between_network.y=f.D67.v
    f3.store_business.self_user_business.other.m=f.C68.v
    f3.store_business.self_user_business.other.y=f.D68.v
    f3.store_business.resource_using_fee.m=f.C69.v
    f3.store_business.resource_using_fee.y=f.D69.v
    f3.store_business.user_change_compensation.m=f.C70.v
    f3.store_business.user_change_compensation.y=f.D70.v
    var f4 = data.business_gain_total.measure_and_network_test_gain
    // console.log(f4)
    f4.m=f.C71.v
    f4.y=f.D71.v
    f4.instrument_measure.m=f.C72.v
    f4.instrument_measure.y=f.D72.v
    f4.network_5G_measure.m=f.C73.v
    f4.network_5G_measure.y=f.D73.v
    f4.wireless_network_measure.m=f.C74.v
    f4.wireless_network_measure.y=f.D74.v
    f4.intnet_measure.m=f.C75.v
    f4.intnet_measure.y=f.D75.v
    f4.intnet_of_thing_measure.m=f.C76.v
    f4.intnet_of_thing_measure.y=f.D76.v
    f4.other_measure.m=f.C77.v
    f4.other_measure.y=f.D77.v
    var f5 = data.business_gain_total.other_gain
    // console.log(f5)
    f5.m=f.C78.v
    f5.y=f.D78.v
    f5.sell_terminal_and_good.m=f.C79.v
    f5.sell_terminal_and_good.y=f.D79.v
    f5.sell_equipment.m=f.C80.v
    f5.sell_equipment.y=f.D80.v
    f5.rent_business.m=f.C81.v
    f5.rent_business.y=f.D81.v
    f5.software_service.m=f.C82.v
    f5.software_service.y=f.D82.v
    f5.tenement_manage.m=f.C83.v
    f5.tenement_manage.y=f.D83.v
    f5.physica_distribution_service.m=f.C84.v
    f5.physica_distribution_service.y=f.D84.v
    f5.other.m=f.C85.v
    f5.other.y=f.D85.v
    console.log(data)
    return data
}
export {read_business_gain}